"""check

Revision ID: a481133f712f
Revises: 006_guest_research
Create Date: 2026-09-10 18:44:42.093856

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a481133f712f'
down_revision: Union[str, None] = '006_guest_research'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('legal_issues',
    sa.Column('matter_id', sa.UUID(), nullable=False),
    sa.Column('intelligence_id', sa.UUID(), nullable=True),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('confidence', sa.String(length=10), nullable=True),
    sa.Column('origin', sa.String(length=30), nullable=False),
    sa.Column('is_selected', sa.Boolean(), nullable=False),
    sa.Column('display_order', sa.Integer(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['intelligence_id'], ['case_intelligence.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['matter_id'], ['matters.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_legal_issues_id'), 'legal_issues', ['id'], unique=False)
    op.create_index(op.f('ix_legal_issues_matter_id'), 'legal_issues', ['matter_id'], unique=False)
    op.create_table('research_notes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('authority_id', sa.UUID(), nullable=False),
    sa.Column('author_id', sa.UUID(), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('length(body) <= 5000', name='chk_notes_length'),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['authority_id'], ['authorities.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_research_notes_authority_id'), 'research_notes', ['authority_id'], unique=False)
    op.drop_index('ix_research_results_query_id', table_name='research_results')
    op.drop_table('research_results')
    op.create_index(op.f('ix_audit_logs_id'), 'audit_logs', ['id'], unique=False)
    op.create_index(op.f('ix_audit_logs_resource_id'), 'audit_logs', ['resource_id'], unique=False)
    op.create_index(op.f('ix_auth_tokens_id'), 'auth_tokens', ['id'], unique=False)
    op.alter_column('authorities', 'session_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('authorities', 'matter_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('authorities', 'proposition_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('authorities', 'selected_by',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('authorities', 'selected_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('authorities', 'relevance_label',
               existing_type=sa.VARCHAR(length=25),
               nullable=False)
    op.drop_index('ix_authorities_matter_id', table_name='authorities')
    op.drop_index('ix_authorities_session_id', table_name='authorities')
    op.create_index('ix_authorities_matter_selected', 'authorities', ['matter_id', 'selected_by'], unique=False)
    op.drop_constraint('authorities_judgment_id_fkey', 'authorities', type_='foreignkey')
    op.drop_constraint('authorities_confirmed_by_id_fkey', 'authorities', type_='foreignkey')
    op.create_foreign_key(None, 'authorities', 'propositions', ['proposition_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'authorities', 'research_sessions', ['session_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'authorities', 'judgments', ['judgment_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'authorities', 'users', ['selected_by'], ['id'], ondelete='CASCADE')
    op.drop_column('authorities', 'extra_metadata')
    op.drop_column('authorities', 'status')
    op.drop_column('authorities', 'notes')
    op.drop_column('authorities', 'confirmed_by_id')
    op.alter_column('case_intelligence', 'status',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=20),
               existing_nullable=False,
               existing_server_default=sa.text("'pending'::character varying"))
    op.create_index(op.f('ix_case_intelligence_id'), 'case_intelligence', ['id'], unique=False)
    op.drop_column('case_intelligence', 'legal_issues')
    op.drop_column('case_intelligence', 'error_message')
    op.drop_column('case_intelligence', 'job_id')
    op.drop_column('case_intelligence', 'suggested_arguments')
    op.drop_column('case_intelligence', 'key_facts')
    op.drop_column('case_intelligence', 'summary')
    op.drop_column('case_intelligence', 'ai_model_used')
    op.create_index(op.f('ix_citations_id'), 'citations', ['id'], unique=False)
    op.create_index(op.f('ix_citations_passage_id'), 'citations', ['passage_id'], unique=False)
    op.create_index(op.f('ix_citations_proposition_id'), 'citations', ['proposition_id'], unique=False)
    op.drop_index('ix_document_chunks_doc_seq', table_name='document_chunks')
    op.drop_index('ix_document_chunks_embedding_hnsw', table_name='document_chunks', postgresql_with={'m': '16', 'ef_construction': '64'}, postgresql_using='hnsw')
    op.create_index(op.f('ix_document_chunks_id'), 'document_chunks', ['id'], unique=False)
    op.drop_index('ix_document_pages_doc_id', table_name='document_pages')
    op.drop_constraint('uq_document_pages_doc_page', 'document_pages', type_='unique')
    op.create_index(op.f('ix_document_pages_document_id'), 'document_pages', ['document_id'], unique=False)
    op.create_index(op.f('ix_document_pages_id'), 'document_pages', ['id'], unique=False)
    op.drop_index('ix_documents_matter_sha256', table_name='documents')
    op.drop_index('ix_documents_object_key', table_name='documents')
    op.create_index(op.f('ix_documents_id'), 'documents', ['id'], unique=False)
    op.create_index(op.f('ix_documents_uploaded_by'), 'documents', ['uploaded_by'], unique=False)
    op.create_unique_constraint(None, 'documents', ['object_key'])
    op.create_index(op.f('ix_draft_exports_id'), 'draft_exports', ['id'], unique=False)
    op.create_index(op.f('ix_draft_questionnaires_id'), 'draft_questionnaires', ['id'], unique=False)
    op.create_index(op.f('ix_draft_sections_draft_version_id'), 'draft_sections', ['draft_version_id'], unique=False)
    op.create_index(op.f('ix_draft_sections_id'), 'draft_sections', ['id'], unique=False)
    op.create_index(op.f('ix_draft_versions_id'), 'draft_versions', ['id'], unique=False)
    op.create_index(op.f('ix_drafts_created_by_id'), 'drafts', ['created_by_id'], unique=False)
    op.create_index(op.f('ix_drafts_id'), 'drafts', ['id'], unique=False)
    op.drop_index('ix_email_outbox_status_created', table_name='email_outbox')
    op.create_index(op.f('ix_email_outbox_id'), 'email_outbox', ['id'], unique=False)
    op.drop_index('ix_judgment_passages_embedding_hnsw', table_name='judgment_passages', postgresql_with={'m': '16', 'ef_construction': '64'}, postgresql_using='hnsw')
    op.create_index(op.f('ix_judgment_passages_id'), 'judgment_passages', ['id'], unique=False)
    op.drop_index('ix_judgments_embedding_hnsw', table_name='judgments', postgresql_with={'m': '16', 'ef_construction': '64'}, postgresql_using='hnsw')
    op.create_index(op.f('ix_judgments_id'), 'judgments', ['id'], unique=False)
    op.create_index(op.f('ix_matter_brief_snapshots_id'), 'matter_brief_snapshots', ['id'], unique=False)
    op.create_index(op.f('ix_matter_brief_snapshots_matter_id'), 'matter_brief_snapshots', ['matter_id'], unique=False)
    op.create_index(op.f('ix_oauth_identities_id'), 'oauth_identities', ['id'], unique=False)
    op.create_index(op.f('ix_propositions_id'), 'propositions', ['id'], unique=False)
    op.drop_index('ix_refresh_tokens_token_hash', table_name='refresh_tokens')
    op.create_index(op.f('ix_refresh_tokens_id'), 'refresh_tokens', ['id'], unique=False)
    op.create_unique_constraint(None, 'refresh_tokens', ['token_hash'])
    op.add_column('research_queries', sa.Column('concept', sa.String(length=200), nullable=True))
    op.add_column('research_queries', sa.Column('generated_by', sa.String(length=20), nullable=False))
    op.add_column('research_queries', sa.Column('rank', sa.Integer(), nullable=False))
    op.alter_column('research_queries', 'session_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_index('ix_research_queries_matter_id', table_name='research_queries')
    op.create_index(op.f('ix_research_queries_session_id'), 'research_queries', ['session_id'], unique=False)
    op.drop_constraint('research_queries_initiated_by_id_fkey', 'research_queries', type_='foreignkey')
    op.drop_constraint('research_queries_proposition_id_fkey', 'research_queries', type_='foreignkey')
    op.drop_constraint('research_queries_matter_id_fkey', 'research_queries', type_='foreignkey')
    op.create_foreign_key(None, 'research_queries', 'research_sessions', ['session_id'], ['id'], ondelete='CASCADE')
    op.drop_column('research_queries', 'search_metadata')
    op.drop_column('research_queries', 'proposition_id')
    op.drop_column('research_queries', 'initiated_by_id')
    op.drop_column('research_queries', 'status')
    op.drop_column('research_queries', 'error_message')
    op.drop_column('research_queries', 'job_id')
    op.drop_column('research_queries', 'matter_id')
    op.drop_index('ix_research_sessions_created_by', table_name='research_sessions')
    op.create_index('ix_research_sessions_matter_created', 'research_sessions', ['matter_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_saved_citations_id'), 'saved_citations', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_saved_citations_id'), table_name='saved_citations')
    op.drop_index('ix_research_sessions_matter_created', table_name='research_sessions')
    op.create_index('ix_research_sessions_created_by', 'research_sessions', ['created_by'], unique=False)
    op.add_column('research_queries', sa.Column('matter_id', sa.UUID(), autoincrement=False, nullable=False))
    op.add_column('research_queries', sa.Column('job_id', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('research_queries', sa.Column('error_message', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('research_queries', sa.Column('status', sa.VARCHAR(length=50), server_default=sa.text("'pending'::character varying"), autoincrement=False, nullable=False))
    op.add_column('research_queries', sa.Column('initiated_by_id', sa.UUID(), autoincrement=False, nullable=True))
    op.add_column('research_queries', sa.Column('proposition_id', sa.UUID(), autoincrement=False, nullable=True))
    op.add_column('research_queries', sa.Column('search_metadata', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'research_queries', type_='foreignkey')
    op.create_foreign_key('research_queries_matter_id_fkey', 'research_queries', 'matters', ['matter_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('research_queries_proposition_id_fkey', 'research_queries', 'propositions', ['proposition_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key('research_queries_initiated_by_id_fkey', 'research_queries', 'users', ['initiated_by_id'], ['id'], ondelete='SET NULL')
    op.drop_index(op.f('ix_research_queries_session_id'), table_name='research_queries')
    op.create_index('ix_research_queries_matter_id', 'research_queries', ['matter_id'], unique=False)
    op.alter_column('research_queries', 'session_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_column('research_queries', 'rank')
    op.drop_column('research_queries', 'generated_by')
    op.drop_column('research_queries', 'concept')
    op.drop_constraint(None, 'refresh_tokens', type_='unique')
    op.drop_index(op.f('ix_refresh_tokens_id'), table_name='refresh_tokens')
    op.create_index('ix_refresh_tokens_token_hash', 'refresh_tokens', ['token_hash'], unique=True)
    op.drop_index(op.f('ix_propositions_id'), table_name='propositions')
    op.drop_index(op.f('ix_oauth_identities_id'), table_name='oauth_identities')
    op.drop_index(op.f('ix_matter_brief_snapshots_matter_id'), table_name='matter_brief_snapshots')
    op.drop_index(op.f('ix_matter_brief_snapshots_id'), table_name='matter_brief_snapshots')
    op.drop_index(op.f('ix_judgments_id'), table_name='judgments')
    op.create_index('ix_judgments_embedding_hnsw', 'judgments', ['embedding'], unique=False, postgresql_with={'m': '16', 'ef_construction': '64'}, postgresql_using='hnsw')
    op.drop_index(op.f('ix_judgment_passages_id'), table_name='judgment_passages')
    op.create_index('ix_judgment_passages_embedding_hnsw', 'judgment_passages', ['embedding'], unique=False, postgresql_with={'m': '16', 'ef_construction': '64'}, postgresql_using='hnsw')
    op.drop_index(op.f('ix_email_outbox_id'), table_name='email_outbox')
    op.create_index('ix_email_outbox_status_created', 'email_outbox', ['status', 'created_at'], unique=False)
    op.drop_index(op.f('ix_drafts_id'), table_name='drafts')
    op.drop_index(op.f('ix_drafts_created_by_id'), table_name='drafts')
    op.drop_index(op.f('ix_draft_versions_id'), table_name='draft_versions')
    op.drop_index(op.f('ix_draft_sections_id'), table_name='draft_sections')
    op.drop_index(op.f('ix_draft_sections_draft_version_id'), table_name='draft_sections')
    op.drop_index(op.f('ix_draft_questionnaires_id'), table_name='draft_questionnaires')
    op.drop_index(op.f('ix_draft_exports_id'), table_name='draft_exports')
    op.drop_constraint(None, 'documents', type_='unique')
    op.drop_index(op.f('ix_documents_uploaded_by'), table_name='documents')
    op.drop_index(op.f('ix_documents_id'), table_name='documents')
    op.create_index('ix_documents_object_key', 'documents', ['object_key'], unique=True)
    op.create_index('ix_documents_matter_sha256', 'documents', ['matter_id', 'sha256'], unique=False)
    op.drop_index(op.f('ix_document_pages_id'), table_name='document_pages')
    op.drop_index(op.f('ix_document_pages_document_id'), table_name='document_pages')
    op.create_unique_constraint('uq_document_pages_doc_page', 'document_pages', ['document_id', 'page_number'])
    op.create_index('ix_document_pages_doc_id', 'document_pages', ['document_id'], unique=False)
    op.drop_index(op.f('ix_document_chunks_id'), table_name='document_chunks')
    op.create_index('ix_document_chunks_embedding_hnsw', 'document_chunks', ['embedding'], unique=False, postgresql_with={'m': '16', 'ef_construction': '64'}, postgresql_using='hnsw')
    op.create_index('ix_document_chunks_doc_seq', 'document_chunks', ['document_id', 'seq'], unique=False)
    op.drop_index(op.f('ix_citations_proposition_id'), table_name='citations')
    op.drop_index(op.f('ix_citations_passage_id'), table_name='citations')
    op.drop_index(op.f('ix_citations_id'), table_name='citations')
    op.add_column('case_intelligence', sa.Column('ai_model_used', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('case_intelligence', sa.Column('summary', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('case_intelligence', sa.Column('key_facts', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('case_intelligence', sa.Column('suggested_arguments', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('case_intelligence', sa.Column('job_id', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('case_intelligence', sa.Column('error_message', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('case_intelligence', sa.Column('legal_issues', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_case_intelligence_id'), table_name='case_intelligence')
    op.alter_column('case_intelligence', 'status',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False,
               existing_server_default=sa.text("'pending'::character varying"))
    op.add_column('authorities', sa.Column('confirmed_by_id', sa.UUID(), autoincrement=False, nullable=True))
    op.add_column('authorities', sa.Column('notes', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('authorities', sa.Column('status', sa.VARCHAR(length=50), server_default=sa.text("'pending'::character varying"), autoincrement=False, nullable=False))
    op.add_column('authorities', sa.Column('extra_metadata', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'authorities', type_='foreignkey')
    op.drop_constraint(None, 'authorities', type_='foreignkey')
    op.drop_constraint(None, 'authorities', type_='foreignkey')
    op.drop_constraint(None, 'authorities', type_='foreignkey')
    op.create_foreign_key('authorities_confirmed_by_id_fkey', 'authorities', 'users', ['confirmed_by_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key('authorities_judgment_id_fkey', 'authorities', 'judgments', ['judgment_id'], ['id'], ondelete='RESTRICT')
    op.drop_index('ix_authorities_matter_selected', table_name='authorities')
    op.create_index('ix_authorities_session_id', 'authorities', ['session_id'], unique=False)
    op.create_index('ix_authorities_matter_id', 'authorities', ['matter_id'], unique=False)
    op.alter_column('authorities', 'relevance_label',
               existing_type=sa.VARCHAR(length=25),
               nullable=True)
    op.alter_column('authorities', 'selected_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('authorities', 'selected_by',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('authorities', 'proposition_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('authorities', 'matter_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('authorities', 'session_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_index(op.f('ix_auth_tokens_id'), table_name='auth_tokens')
    op.drop_index(op.f('ix_audit_logs_resource_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_id'), table_name='audit_logs')
    op.create_table('research_results',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), autoincrement=False, nullable=False),
    sa.Column('query_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('matter_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('judgment_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('relevance_score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('relevance_explanation', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('rank', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('selected_by_lawyer', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['judgment_id'], ['judgments.id'], name='research_results_judgment_id_fkey', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['matter_id'], ['matters.id'], name='research_results_matter_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['query_id'], ['research_queries.id'], name='research_results_query_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='research_results_pkey')
    )
    op.create_index('ix_research_results_query_id', 'research_results', ['query_id'], unique=False)
    op.drop_index(op.f('ix_research_notes_authority_id'), table_name='research_notes')
    op.drop_table('research_notes')
    op.drop_index(op.f('ix_legal_issues_matter_id'), table_name='legal_issues')
    op.drop_index(op.f('ix_legal_issues_id'), table_name='legal_issues')
    op.drop_table('legal_issues')
    # ### end Alembic commands ###